GroepBAvans/project-moesland

- .eslintrc.js
- backend/app.js
- backend/middleware/auth.js
- backend/middleware/debug.js
- backend/middleware/security.js
- backend/models.js
- backend/models/authToken.js
- backend/models/role.js
- backend/models/user.js
- backend/repository/authToken.js
- backend/repository/role.js
- backend/repository/user.js
- backend/routes/api/auth.js
- backend/routes/api/authToken/index.js
- backend/routes/api/role/index.js
- backend/routes/api/user/index.js
- backend/routes/index.js
- backend/seed/dataSeeder.js
- backend/seed/rolesSeeder.js
- backend/seed/userSeeder.js
- backend/services/auth.service.js
- backend/services/database.js
> Login system/eslint error fix

- backend/models/userImage.js
> Create userImage model

- backend/repository/userImage.js
- backend/routes/api/userImage/index.js
Backend get all user images.
GET request to `/api/userImage/`
> Backend get all user images

- backend/repository/image.js
- backend/repository/newsArticle.js
- backend/routes/api/newsArticle/create.js
- backend/routes/api/newsArticle/delete.js
- backend/routes/api/newsArticle/index.js
- backend/routes/api/newsArticle/update.js
- backend/routes/index.js
- management/src/layout/default.js
- management/src/layout/footer.js
- management/src/layout/navbar.js
- management/src/modules/article/modalDelete.js
- management/src/modules/user/modalAdd.js
- management/src/modules/user/modalDelete.js
- management/src/modules/user/modalUpdate.js
- management/src/pages/articles/create.js
- management/src/pages/articles/overview.js
- management/src/pages/articles/update.js
- management/src/pages/userManagement.js
- management/src/styles/style.css
Improvements:
- Code cleanup
- Styling, language and grammar
- Autofill username on user update
- News article deletion warning
- News article input errors/warnings
- And probably more I can't think of off the top of my head :)
> General improvements, pt. 1

- backend/models.js
- backend/models/event.js
- backend/seeds/dataSeeder.js
- backend/seeds/eventSeeder.js
> Event management/database

- backend/package-lock.json
- backend/package.json
- backend/repository/authToken.js
- backend/repository/image.js
- backend/repository/newsArticle.js
- backend/repository/role.js
- backend/repository/user.js
- backend/repository/userImage.js
- backend/routes/api/newsArticle/create.js
- backend/routes/api/newsArticle/delete.js
- backend/routes/api/newsArticle/update.js
Fixed most/all CodeQL errors. Preferrably test everything in the backend/management.
> Fixed most/all CodeQL errors

- management/src/layout/footer.js
- management/src/layout/navbar.js
- management/src/pages/articles/overview.js
- management/src/pages/home.js
- management/src/pages/userManagement.js
- management/src/styles/style.css
> Cleanup + moesland font for headers

- backend/package-lock.json
- backend/package.json
- backend/repository/event.js
- backend/routes/api/event/add.js
- backend/routes/api/event/delete.js
- backend/routes/api/event/update.js
- backend/routes/index.js
> Event management/create update delete

- management/.env
- management/.env.example
.env moet niet mee gecommit worden. Daarom verplaatst naar .env.example
> Rename .env to .env.example

- backend/seeds/eventSeeder.js
> event seeder fix

- backend/routes/index.js
> No longer require superadmin

- backend/package-lock.json
- management/src/pages/events/overview.js
**Testen:**
- Ga naar Evenementen.
- Maak een aantal evenementen en optochten aan.
- Probeer te filteren.
> Fixed parade filtering

- backend/models/vote.js
- backend/package-lock.json
- backend/repository/vote.js
- backend/routes/api/vote.js
- moesland-app/yarn.lock
> ML 87 voting database

- backend/package-lock.json
- management/src/pages/events/overview.js
**Testen:**
- Maak een aantal evenementen en optochten aan.
- Kijk in het totaaloverzicht.
> Parade location in overview

- management/src/layout/navbar.js
> Frontend hotfix

- backend/repository/userImage.js
- backend/routes/api/userImage/index.js
- management/src/layout/navbar.js
- management/src/pages/photoManagement/approvedPhotoManagement.js
- management/src/pages/photoManagement/declinedPhotoManagement.js
- management/src/pages/photoManagement/photoManagement.js
- management/src/routing.js
- package-lock.json
- package.json
**Testen:**
- Zorg voor een paar user images (via Postman of de app).
- Ga naar Goedgekeurde gebruikersfoto's.
- Probeer alle functies uit.
> Approved photos page

- moesland-app/src/routes/CalendarView.jsx
- moesland-app/src/styles/CalendarStyles.js
Changes to the app calendar based on Twan's feedback from sprintreview 5.
> removed important event styling

- moesland-app/app.json
- moesland-app/package-lock.json
- moesland-app/package.json
- moesland-app/src/routes/PhotoContentView.jsx
- moesland-app/yarn.lock
> camera app opens

- backend/repository/image.js
- backend/routes/api/newsArticle/create.js
- backend/routes/api/newsArticle/update.js
Fixed news article image crashing and not updating
> Fixed news article image crashing and not updating

- management/src/layout/navbar.js
Fixed the disappearing navbar in management.
> Fixed disappearing navbar

- backend/routes/api/newsArticle/update.js
- backend/routes/api/userImage/delete.js
- management/src/modules/newsArticles/modalDelete.js
- management/src/modules/userImage/modalDelete.js
- management/src/pages/articles/create.js
- management/src/pages/articles/overview.js
- management/src/pages/articles/update.js
- management/src/pages/photoManagement/approvedPhotoManagement.js
- management/src/pages/photoManagement/declinedPhotoManagement.js
- management/src/pages/photoManagement/photoManagement.js
- management/src/services/ApiClient.js
- management/src/services/newsArticle.js
- management/src/services/userImage.js
- News article refactoring
- User image refactoring
- Nummer 3 van Twan's mailtje (gedownloade foto's verwijderen)
> Refactoring bjorn

- backend/models/newsArticle.js
> No more invalid JSON for news articles
